# Generated by Django 3.0.2 on 2020-01-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetaDataTerm',
            fields=[
                ('term_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name=20)),
                ('name', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtractiveDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name=20)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('signer', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=225, null=True)),
                ('url', models.CharField(max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('enforced_date', models.DateField(blank=True, null=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('is_over_due', models.PositiveSmallIntegerField(verbose_name=1)),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name=20)),
                ('name', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfDraftedDocument',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name=20)),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField()),
                ('last_update_time', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='SelfDraftedDocumentMetaData',
            fields=[
                ('meta_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name=20)),
                ('term_value', models.CharField(max_length=1500)),
                ('last_update_time', models.DateTimeField()),
                ('self_drafted_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.SelfDraftedDocument')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.DocumentMetaDataTerm')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractiveDocumentMetaData',
            fields=[
                ('meta_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name=20)),
                ('term_value', models.CharField(max_length=1500)),
                ('last_update_time', models.DateTimeField()),
                ('extractive_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.ExtractiveDocument')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.DocumentMetaDataTerm')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractiveDocumentSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_time', models.DateTimeField()),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractive_document_destination', to='laws.ExtractiveDocument')),
                ('relation_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.RelationType')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractive_document_source', to='laws.ExtractiveDocument')),
            ],
            options={
                'unique_together': {('source_id', 'destination_id')},
            },
        ),
    ]
